### ISSUE TITLE
Need License?

### ISSUE THREAD

**Issue by magicJie** [ONLYOFFICE/Kubernetes-DocSpace#95]
I have successfully completed the installation in the Kubernetes cluster (community edition), but when trying to access the service, it's asking for a license. Where can I obtain this license?
![image](https://github.com/ONLYOFFICE/Kubernetes-DocSpace/assets/6937525/cde7460b-f293-428e-a74b-0bc51a28c022)

**Comment by alexanderonlyoffice** [comment]
@magicJie, we fixed the problem on **main** branch, you have to re-deploy the installation using the updated repo.

**Comment by magicJie** [comment]
I have reinstalled it, and the license issue has been resolved. However, after enabling the ingress, I encountered the following error when editing the document：
![image](https://github.com/ONLYOFFICE/Kubernetes-DocSpace/assets/6937525/4f510c95-62ba-412c-90c1-a0de3dd68617)

**Comment by alexanderonlyoffice** [comment]
@magicJie, we are analyzing the case.

**Comment by magicJie** [comment]
> 
Thank you for your help and look forward to solving the problem。

**Comment by alexanderonlyoffice** [comment]
@magicJie, please do the following: you need to indicate the list of networks or proxy servers ips in parameter [connections.appKnownProxies](https://github.com/ONLYOFFICE/Kubernetes-DocSpace/blob/main/values.yaml#L148) that you are using in front of DocSpace. For example, if you are using only Ingress Controller and its pods are located in the same network as DocSpace pods you can indicate it like this: 

```
connections:
  appKnownProxies: "10.244.0.0/16"
```

If several subnetworks are used, you can indicate the list: 

```
connections:
  appKnownProxies: "10.244.0.0/16,10.245.0.0/16,10.135.0.0/16"
```

There might be CSP entries in browser dev tools, but they are not affecting document editing. We are investigating the case further.

**Comment by magicJie** [comment]
@alexanderonlyoffice ,Thank you for your suggestion. My problem has been solved.

**Comment by alexanderonlyoffice** [comment]
@magicJie, I am glad the issue has been solved.
